import {createClient} from '@supabase/supabase-js';

export const client = createClient('https://psqreewnwkoifzmigerp.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzcXJlZXdud2tvaWZ6bWlnZXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg3ODQzOTIsImV4cCI6MjA0NDM2MDM5Mn0.83N1kZTL9jd0HymPIGr9oClgPG-Reg4lLJkV2wnnink');